language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

virtualenv:
  system_site_packages: true
  
matrix:
  include:
    - name: "MacOS py36"
      os: osx
      language: generic
      env:
        - PIP=pip3
        - CIBW_BUILD="cp36-*"
        - COVER="on"

env:
  global:
    - TWINE_USERNAME=mcuntz

before_install:
    - python3 -m pip install -U pip
    - python3 -m pip install -U pytest
    - python3 -m pip install -U pytest-cov
    - python3 -m pip install -U coveralls

install:
    - python3 -m pip install -r tests/requirements_test.txt
    - python3 -m pip install -r docs/requirements.txt
    - python3 -m pip install .

script:
  # create wheels
  - sudo python3 -m pip install cibuildwheel==0.11.1
  - cibuildwheel --output-dir wheelhouse
  # create source dist for pypi and create coverage (only once for linux py3.6)
  - |
    if [[ $COVER == "on" ]]; then
      rm -rf dist
      python3 -m pip install -U setuptools
      python3 -m pip install pytest-cov coveralls
      python3 -m pip install numpy scipy six
      python3 -m pip install schwimmbad
      python3 -m pip install -r docs/requirements.txt
      python3 setup.py sdist
      python3 -m pytest --cov pyeee --cov-report term-missing -v tests/
      python3 -m coveralls
    fi

after_script:
  # pypi upload (test allways)
  - python3 -m pip install twine
  - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz

after_success:
  # pypi upload (test allways and official on TAG)
  - python3 -m pip install twine
  - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*.tar.gz
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m twine upload --skip-existing wheelhouse/*.whl
      python3 -m twine upload --skip-existing dist/*.tar.gz
    fi

notifications:
  email:
    recipients:
    - mc@macu.de

sudo: False

deploy:
  user: mcuntz
  password:
    secure: AMQ6+uKypcRqM2qB+oqsqtIWIBsyR0Gnhue14vJHquvmHHHq/4RoGOoUZHhDFdNTe7C2xBTmVPqhJvyBLnGYJ2jJVKAqlvH1IsxW6n1BcY8cCr2nG81XHZzTl0OAEpaWDg9k3GjdrD8KZW7O/EdEb4V5qHJyMdVnXz22Ls0DdBcgITOCdxS7wPqmCKYu0qzVk+JTSOc86JUZ1fp2q1DZd9RDT6GRzLuFLe2kIXrQKvZFI3bG97SYKh+m6v8bnXZpqYN1s8EqKRtKwGR0Jr94YgD3awjLGfzqOLjwg2PjTnlzYwu9uQlupAkv93gWexuqWzVoy4ctmPHEBF+ifu9HVN8svJmoiK2aJ8DgPGkqe62JNxCRZtK1utWpDXblP6apyTT1qiOlxwFuFUlWk/zv0V9/Pcrz/8yTDp6KrkH+6kCypq/ql80mwsLxIbPuRgLQa0zzGnGMIR3XS5zGd9kms2IoBh14lES72vyvbZ0K9waGcEBehPdh624mR3MsOY2Ex9fibLG1UMRYjmk9fkWz5sXpSDwiJzHvlD8rtQ4PIvCIaPpIN8OtbidAts3vJ7WvK90ok0GwAI4gyVT/YRTp43xoPnEGQ1j1Hlf7vFejpUfi1dw+FkwScPC4yLAvbP5BHHI49neCeE3H3e0vC5J4cV0vvLStTx4aYnFjhAlZN4Y=
